In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [54]:
x=pd.read_csv(r"C:\Users\shivam parihari\Downloads\heart.csv")
x.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [55]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['Sex']=le.fit_transform(x['Sex'])
x['ChestPainType']=le.fit_transform(x['ChestPainType'])
x['RestingECG']=le.fit_transform(x['RestingECG'])
x['ExerciseAngina']=le.fit_transform(x['ExerciseAngina'])
x['ST_Slope']=le.fit_transform(x['ST_Slope'])

In [56]:
x.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [57]:
x.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [58]:
ip=x.drop(columns='HeartDisease')

In [59]:
op=x.HeartDisease

In [60]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(ip,op,train_size=0.85)

In [61]:
from sklearn.preprocessing import StandardScaler

standard=StandardScaler()

In [62]:
xtrain = standard.fit_transform(xtrain)
xtest = standard.transform(xtest)

In [63]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [64]:
models={
    "sv": SVC(),
    "lr": LogisticRegression(),
    "knn": KNeighborsClassifier(),
    "nb": GaussianNB(),
    "dt": DecisionTreeClassifier()
}

In [65]:
result=[]

In [66]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

In [67]:
for name,model in models.items():
    model.fit(xtrain,ytrain)
    pred=model.predict(xtest)
    acc=accuracy_score(ytest,pred)
    cm=confusion_matrix(ytest,pred)
    f1=f1_score(ytest,pred)
    result.append({
        'model':name,
        'accuracy':round(acc,4),
        'f1 score':round(f1,4)
        
    })

In [68]:
result

[{'model': 'sv', 'accuracy': 0.8333, 'f1 score': 0.8535},
 {'model': 'lr', 'accuracy': 0.8406, 'f1 score': 0.8608},
 {'model': 'knn', 'accuracy': 0.8478, 'f1 score': 0.8645},
 {'model': 'nb', 'accuracy': 0.8551, 'f1 score': 0.8684},
 {'model': 'dt', 'accuracy': 0.7899, 'f1 score': 0.8054}]

In [69]:
import joblib
joblib.dump(models["nb"],'naive_bayes1.pkl')
joblib.dump(standard,'standard1.pkl')
joblib.dump(ip.columns.to_list(),'columns1.pkl')

['columns1.pkl']