In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [35]:
x=pd.read_csv(r"C:\Users\shivam parihari\Downloads\titanic dataset.csv")
x.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
x.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [78]:
x['Age'].fillna(x['Age'].mean(),inplace=True)
x.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [38]:
d=x.describe(include='all')
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,891.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,13.002015,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,22.000000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,29.699118,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,35.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [39]:
x['Cabin'].fillna('?',inplace=True)
x['Embarked'].fillna('?',inplace=True)

In [40]:
x['Embarked']=x['Embarked'].replace('?',d['Embarked'][2])
x['Cabin']=x['Cabin'].replace('?',d['Cabin'][2])

In [41]:
x.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['Sex']=le.fit_transform(x['Sex'])
x['Name']=le.fit_transform(x['Name'])
x['Ticket']=le.fit_transform(x['Ticket'])
x['Cabin']=le.fit_transform(x['Cabin'])
x['Embarked']=le.fit_transform(x['Embarked'])

In [43]:
ip=x.drop(columns='Survived')
ip
op=x.Survived

In [65]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(ip,op,train_size=0.85)

In [66]:
from sklearn.preprocessing import StandardScaler

standard=StandardScaler()
standard.fit_transform(xtrain)
standard.fit_transform(xtest)

array([[ 1.713855  , -1.70274518,  0.34109182, ..., -0.01823246,
         0.53987131, -1.9580656 ],
       [ 0.82369812,  0.86093857, -0.10620139, ..., -0.48555959,
        -0.30647847,  0.55275536],
       [ 1.17898004,  0.86093857, -1.40492117, ..., -0.3327921 ,
        -0.30647847, -1.9580656 ],
       ...,
       [-0.38660289,  0.86093857,  0.38032807, ..., -0.15131237,
        -0.30647847, -0.70265512],
       [-1.06593314,  0.86093857,  0.3057792 , ..., -0.48366759,
        -0.30647847,  0.55275536],
       [ 1.54207034, -0.4209033 ,  0.78446141, ..., -0.36279595,
        -0.30647847,  0.55275536]])

In [67]:
from sklearn.svm import SVC

In [68]:
model=SVC(kernel='rbf')

In [69]:
model.fit(xtrain,ytrain)

SVC()

In [70]:
pred=model.predict(xtest)

In [71]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,pred)

0.6567164179104478

In [72]:
from sklearn.model_selection import cross_val_score

In [74]:
ip1=standard.fit_transform(ip)

In [ ]:
scores=cross_val_score(model,ip1,op,cv=5,scoring='accuracy')
print(scores)
# scores is the array of accuracy scores when we got by cross validation

[0.83240223 0.81460674 0.83146067 0.79775281 0.84269663]

In [77]:
print(scores.mean())

0.8237838177138912